let tesztSor = [
    {
        targy: 'Webszerkesztés',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a HTML?',
        valaszok: [
            'Hypertext Markup Language',
            'Hypertext Markdown Language',
            'Hypertype Markup Language',
            'Hypertext Markup Literature',
        ],
        joValasz: 'Hypertext Markup Language',
        kep: 'https://www.oxfordwebstudio.com/user/pages/06.da-li-znate/sta-je-html/sta-je-html.jpg',
    },
    {
        targy: 'Webszerkesztés',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a CSS?',
        valaszok: [
            'Cascading Style Sheets',
            'Cascading Stylish Sheets',
            'Cascading Stylish Sheet',
            'Cascading Style Sheet',
        ],
        joValasz: 'Cascading Style Sheets',
        kep: 'https://capity.hu/kep/58/webfejlesztes.jpg',
    },
    {
        targy: 'Python',
        tipus: 'radio',
        kerdes: 'A Python az fordított vagy értelmezett programozási nyelv?',
        valaszok: ['fordított', 'értelmezett'],
        joValasz: 'értelmezett',
        kep: 'https://www.malnasuli.hu/wp-content/uploads/2020/01/python-logo-master-v3-TM.png',
    },
    {
        targy: 'Webszerkesztés',
        tipus: 'check',
        kerdes: 'Mi nem igaz a HTML-re?',
        valaszok: [
            'Fordított programozási nyelv',
            'Jelölőnyelv',
            'Elemeket használ a tartalom tagolására',
            'Nem használ címkéket (tag)',
        ],
        joValaszok: [
            'Fordított programozási nyelv',
            'Nem használ címkéket (tag)',
        ],
        kep: 'https://www.freecodecamp.org/news/content/images/2021/08/html.png',
    },
    {
        targy: 'Webszerkesztés',
        tipus: 'check',
        kerdes: 'Mi nem igaz a HTML elemekre?',
        valaszok: [
            'Minden elemnek van külön nyitó- és zárócímkéje',
            'Mindig a zárócímkében helyezzük el a /-jelet',
            'Minden elemnek van tartalma (content)',
            'a &lt;p&gt;&lt;/p&gt; és a &lt;P&gt;&lt;/P&gt; ugyanúgy paragrafust hoz létre',
        ],
        joValaszok: [
            'Minden elemnek van külön nyitó- és zárócímkéje',
            'Minden elemnek van tartalma (content)',
        ],
        kep: 'https://media.licdn.com/dms/image/D4D12AQGMSvEmt00Wxw/article-cover_image-shrink_600_2000/0/1710472277513?e=2147483647&v=beta&t=Dv8_W7mbHSy1-rPtg6vWc08litiaHv7z6dFJfL2yfXA',
    },
    {
        targy: 'It Alapok I.',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a CPU?',
        valaszok: [
            'Central Processing Unit',
            'Central Programmable Unit',
            'Common Processing Unit',
            'Central Progressive Unit',
        ],
        joValasz: 'Central Processing Unit',
        kep: 'https://intec.hu/wp-content/uploads/cpu-300x245.jpg',
    },
    {
        targy: 'It Alapok I.',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a GPU?',
        valaszok: [
            'Graphics Processing Unit',
            'Graphical Processing Unit',
            'Graphics Programmable Unit',
            'Graphical Programmable Unit',
        ],
        joValasz: 'Graphics Processing Unit',
        kep: 'https://miro.medium.com/v2/resize:fit:1024/1*VgG01qUdBx2OMlCYIa2SRA.jpeg',
    },
    {
        targy: 'It Alapok II. (hálózat)',
        tipus: 'radio',
        kerdes: 'A Cisco Packet Tracer egy vizuális szimulációs eszköz?',
        valaszok: ['Igaz', 'Hamis'],
        joValasz: 'Igaz',
        kep: 'https://networkslearning.com/wp-content/uploads/2020/02/Screenshot-2020-02-15-at-15.54.25.png',
    },
];
