let tesztSor = [
    {
        targy: 'Webszerkesztés',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a HTML?',
        valaszok: [
            'Hypertext Markup Language',
            'Hypertext Markdown Language',
            'Hypertype Markup Language',
            'Hypertext Markup Literature',
        ],
        joValasz: 'Hypertext Markup Language',
        kep: 'https://www.oxfordwebstudio.com/user/pages/06.da-li-znate/sta-je-html/sta-je-html.jpg',
    },
    {
        targy: 'Webszerkesztés',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a CSS?',
        valaszok: [
            'Cascading Style Sheets',
            'Cascading Stylish Sheets',
            'Cascading Stylish Sheet',
            'Cascading Style Sheet',
        ],
        joValasz: 'Cascading Style Sheets',
        kep: 'https://capity.hu/kep/58/webfejlesztes.jpg',
    },
    {
        targy: 'Python',
        tipus: 'radio',
        kerdes: 'A Python az fordított vagy értelmezett programozási nyelv?',
        valaszok: ['fordított', 'értelmezett'],
        joValasz: 'értelmezett',
        kep: 'https://www.malnasuli.hu/wp-content/uploads/2020/01/python-logo-master-v3-TM.png',
    },
    {
        targy: 'Webszerkesztés',
        tipus: 'check',
        kerdes: 'Mi nem igaz a HTML-re?',
        valaszok: [
            'Fordított programozási nyelv',
            'Jelenleg a 6.2-es változatát használjuk',
            'Jelölőnyelv',
            'Elemeket használ a tartalom tagolására',
            'Nem használ címkéket (tag)',
        ],
        joValaszok: [
            'Fordított programozási nyelv',
            'Jelenleg a 6.2-es változatát használjuk',
            'Nem használ címkéket (tag)',
        ],
        kep: 'https://www.freecodecamp.org/news/content/images/2021/08/html.png',
    },
    {
        targy: 'Webszerkesztés',
        tipus: 'check',
        kerdes: 'Mi nem igaz a HTML elemekre?',
        valaszok: [
            'Minden elemnek van külön nyitó- és zárócímkéje',
            'Mindig a zárócímkében helyezzük el a /-jelet',
            'Minden elemnek van tartalma (content)',
            'a &lt;p&gt;&lt;/p&gt; és a &lt;P&gt;&lt;/P&gt; ugyanúgy paragrafust hoz létre',
        ],
        joValaszok: [
            'Minden elemnek van külön nyitó- és zárócímkéje',
            'Minden elemnek van tartalma (content)',
        ],
        kep: 'https://media.licdn.com/dms/image/D4D12AQGMSvEmt00Wxw/article-cover_image-shrink_600_2000/0/1710472277513?e=2147483647&v=beta&t=Dv8_W7mbHSy1-rPtg6vWc08litiaHv7z6dFJfL2yfXA',
    },
    {
        targy: 'It Alapok I.',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a CPU?',
        valaszok: [
            'Central Processing Unit',
            'Central Programmable Unit',
            'Common Processing Unit',
            'Central Progressive Unit',
        ],
        joValasz: 'Central Processing Unit',
        kep: 'https://intec.hu/wp-content/uploads/cpu-300x245.jpg',
    },
    {
        targy: 'It Alapok I.',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a GPU?',
        valaszok: [
            'Graphics Processing Unit',
            'Graphical Processing Unit',
            'Graphics Programmable Unit',
            'Graphical Programmable Unit',
        ],
        joValasz: 'Graphics Processing Unit',
        kep: 'https://miro.medium.com/v2/resize:fit:1024/1*VgG01qUdBx2OMlCYIa2SRA.jpeg',
    },
    {
        targy: 'It Alapok II. (hálózat)',
        tipus: 'radio',
        kerdes: 'A Cisco Packet Tracer egy vizuális szimulációs eszköz.',
        valaszok: ['Igaz', 'Hamis'],
        joValasz: 'Igaz',
        kep: 'https://networkslearning.com/wp-content/uploads/2020/02/Screenshot-2020-02-15-at-15.54.25.png',
    },
    {
        targy: 'Szoftvertesztelés',
        tipus: 'radio',
        kerdes: 'Létezik unit teszt.',
        valaszok: ['Igaz', 'Hamis'],
        joValasz: 'Igaz',
        kep: 'https://ithub.hu/images/blog/unit-test-mistakes.jpg',
    },
    {
        targy: 'Asztali alkalmazások',
        tipus: 'radio',
        kerdes: 'A C# egy objektumorientált programozási nyelv.',
        valaszok: ['Igaz', 'Hamis'],
        joValasz: 'Igaz',
        kep: 'https://cdn-ckjba.nitrocdn.com/XvHIXtRQMUYzLjoXbfBpiwAcydcSSOVj/assets/images/optimized/rev-81f45bc/www.ciat.edu/wp-content/uploads/2022/12/c-sharp-blog.jpeg',
    },
    {
        targy: 'Adatbázis-kezelés',
        tipus: 'radio',
        kerdes: 'A MongoDb egy SQL adatbázis.',
        valaszok: ['Igaz', 'Hamis'],
        joValasz: 'Hamis',
        kep: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShLkVVZFiwIEqwzm1SXhP7N7_dfIGchUww0w&s',
    },
    {
        targy: 'Webprogramozás',
        tipus: 'radio',
        kerdes: 'Minek a rövidítése a DOM?',
        valaszok: [
            'Document Object Model',
            'Document Oriented Model',
            'Data Object Model',
            'Dictionary Oriented Model',
        ],
        joValasz: 'Document Object Model',
        kep: 'https://www.aluracursos.com/blog/assets/que-es-dom/arvore-dom.png',
    },
    {
        targy: 'Frontend programozás',
        tipus: 'radio',
        kerdes: 'A React egy JavaScript könyvtár.',
        valaszok: ['Igaz', 'Hamis'],
        joValasz: 'Igaz',
        kep: 'https://media.licdn.com/dms/image/C4E12AQFdVr18zUa17Q/article-cover_image-shrink_720_1280/0/1624637761724?e=2147483647&v=beta&t=txL8oZw9vpsEAev7vCuRj8GQpDmbmG9FMUnRDtRzXaY',
    },
    {
        targy: 'Backend programozás',
        tipus: 'radio',
        kerdes: 'A Node.js egy JavaScript futtatókörnyezet.',
        valaszok: ['Igaz', 'Hamis'],
        joValasz: 'Igaz',
        kep: 'https://media.licdn.com/dms/image/v2/D4D12AQF1btzrvx64aQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1698242399109?e=2147483647&v=beta&t=_V-6ub-4NLvaWr2Nmoj4IhUoIP4QyrUTx-GBQXWXQQs',
    },
];
